# 数据库配置
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/your_database
    username: your_admin_username
    password: your_admin_password
    driver-class-name: org.postgresql.Driver

  # JPA配置
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Flyway配置
flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration